// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: api.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateGameInputs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userid uint32 `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
}

func (x *CreateGameInputs) Reset() {
	*x = CreateGameInputs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGameInputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameInputs) ProtoMessage() {}

func (x *CreateGameInputs) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameInputs.ProtoReflect.Descriptor instead.
func (*CreateGameInputs) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGameInputs) GetUserid() uint32 {
	if x != nil {
		return x.Userid
	}
	return 0
}

type CreateGameOutputs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gameid      uint32 `protobuf:"varint,1,opt,name=gameid,proto3" json:"gameid,omitempty"`
	Featuredmap string `protobuf:"bytes,2,opt,name=featuredmap,proto3" json:"featuredmap,omitempty"`
}

func (x *CreateGameOutputs) Reset() {
	*x = CreateGameOutputs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGameOutputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameOutputs) ProtoMessage() {}

func (x *CreateGameOutputs) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameOutputs.ProtoReflect.Descriptor instead.
func (*CreateGameOutputs) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *CreateGameOutputs) GetGameid() uint32 {
	if x != nil {
		return x.Gameid
	}
	return 0
}

func (x *CreateGameOutputs) GetFeaturedmap() string {
	if x != nil {
		return x.Featuredmap
	}
	return ""
}

type JoinGameInputs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gameid uint32 `protobuf:"varint,1,opt,name=gameid,proto3" json:"gameid,omitempty"`
	Userid uint32 `protobuf:"varint,2,opt,name=userid,proto3" json:"userid,omitempty"`
}

func (x *JoinGameInputs) Reset() {
	*x = JoinGameInputs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinGameInputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGameInputs) ProtoMessage() {}

func (x *JoinGameInputs) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGameInputs.ProtoReflect.Descriptor instead.
func (*JoinGameInputs) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *JoinGameInputs) GetGameid() uint32 {
	if x != nil {
		return x.Gameid
	}
	return 0
}

func (x *JoinGameInputs) GetUserid() uint32 {
	if x != nil {
		return x.Userid
	}
	return 0
}

type JoinGameOutputs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Otherusersid uint32 `protobuf:"varint,1,opt,name=otherusersid,proto3" json:"otherusersid,omitempty"`
	Featuredmap  string `protobuf:"bytes,2,opt,name=featuredmap,proto3" json:"featuredmap,omitempty"`
}

func (x *JoinGameOutputs) Reset() {
	*x = JoinGameOutputs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinGameOutputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGameOutputs) ProtoMessage() {}

func (x *JoinGameOutputs) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGameOutputs.ProtoReflect.Descriptor instead.
func (*JoinGameOutputs) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (x *JoinGameOutputs) GetOtherusersid() uint32 {
	if x != nil {
		return x.Otherusersid
	}
	return 0
}

func (x *JoinGameOutputs) GetFeaturedmap() string {
	if x != nil {
		return x.Featuredmap
	}
	return ""
}

type Move struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X         int32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y         int32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Direction int32 `protobuf:"varint,3,opt,name=direction,proto3" json:"direction,omitempty"`
}

func (x *Move) Reset() {
	*x = Move{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Move) ProtoMessage() {}

func (x *Move) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Move.ProtoReflect.Descriptor instead.
func (*Move) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

func (x *Move) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Move) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Move) GetDirection() int32 {
	if x != nil {
		return x.Direction
	}
	return 0
}

type MoveInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pawnid uint32  `protobuf:"varint,1,opt,name=pawnid,proto3" json:"pawnid,omitempty"`
	Move   []*Move `protobuf:"bytes,2,rep,name=move,proto3" json:"move,omitempty"`
}

func (x *MoveInput) Reset() {
	*x = MoveInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveInput) ProtoMessage() {}

func (x *MoveInput) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveInput.ProtoReflect.Descriptor instead.
func (*MoveInput) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{5}
}

func (x *MoveInput) GetPawnid() uint32 {
	if x != nil {
		return x.Pawnid
	}
	return 0
}

func (x *MoveInput) GetMove() []*Move {
	if x != nil {
		return x.Move
	}
	return nil
}

type MoveInputs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userid    uint32       `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
	Gameid    uint32       `protobuf:"varint,2,opt,name=gameid,proto3" json:"gameid,omitempty"`
	Moveinput []*MoveInput `protobuf:"bytes,3,rep,name=moveinput,proto3" json:"moveinput,omitempty"`
}

func (x *MoveInputs) Reset() {
	*x = MoveInputs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveInputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveInputs) ProtoMessage() {}

func (x *MoveInputs) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveInputs.ProtoReflect.Descriptor instead.
func (*MoveInputs) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{6}
}

func (x *MoveInputs) GetUserid() uint32 {
	if x != nil {
		return x.Userid
	}
	return 0
}

func (x *MoveInputs) GetGameid() uint32 {
	if x != nil {
		return x.Gameid
	}
	return 0
}

func (x *MoveInputs) GetMoveinput() []*MoveInput {
	if x != nil {
		return x.Moveinput
	}
	return nil
}

type MoveOutputs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OK bool `protobuf:"varint,1,opt,name=OK,proto3" json:"OK,omitempty"`
}

func (x *MoveOutputs) Reset() {
	*x = MoveOutputs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveOutputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveOutputs) ProtoMessage() {}

func (x *MoveOutputs) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveOutputs.ProtoReflect.Descriptor instead.
func (*MoveOutputs) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{7}
}

func (x *MoveOutputs) GetOK() bool {
	if x != nil {
		return x.OK
	}
	return false
}

type LastMovesInputs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gameid uint32 `protobuf:"varint,1,opt,name=gameid,proto3" json:"gameid,omitempty"`
	Round  uint32 `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
}

func (x *LastMovesInputs) Reset() {
	*x = LastMovesInputs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LastMovesInputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LastMovesInputs) ProtoMessage() {}

func (x *LastMovesInputs) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LastMovesInputs.ProtoReflect.Descriptor instead.
func (*LastMovesInputs) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{8}
}

func (x *LastMovesInputs) GetGameid() uint32 {
	if x != nil {
		return x.Gameid
	}
	return 0
}

func (x *LastMovesInputs) GetRound() uint32 {
	if x != nil {
		return x.Round
	}
	return 0
}

type LastMovesOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userid    uint32 `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
	Gameid    uint32 `protobuf:"varint,2,opt,name=gameid,proto3" json:"gameid,omitempty"`
	Pawnid    uint32 `protobuf:"varint,3,opt,name=pawnid,proto3" json:"pawnid,omitempty"`
	X         int32  `protobuf:"varint,4,opt,name=x,proto3" json:"x,omitempty"`
	Y         int32  `protobuf:"varint,5,opt,name=y,proto3" json:"y,omitempty"`
	Direction int32  `protobuf:"varint,6,opt,name=direction,proto3" json:"direction,omitempty"`
	Round     int32  `protobuf:"varint,7,opt,name=round,proto3" json:"round,omitempty"`
}

func (x *LastMovesOutput) Reset() {
	*x = LastMovesOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LastMovesOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LastMovesOutput) ProtoMessage() {}

func (x *LastMovesOutput) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LastMovesOutput.ProtoReflect.Descriptor instead.
func (*LastMovesOutput) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{9}
}

func (x *LastMovesOutput) GetUserid() uint32 {
	if x != nil {
		return x.Userid
	}
	return 0
}

func (x *LastMovesOutput) GetGameid() uint32 {
	if x != nil {
		return x.Gameid
	}
	return 0
}

func (x *LastMovesOutput) GetPawnid() uint32 {
	if x != nil {
		return x.Pawnid
	}
	return 0
}

func (x *LastMovesOutput) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *LastMovesOutput) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *LastMovesOutput) GetDirection() int32 {
	if x != nil {
		return x.Direction
	}
	return 0
}

func (x *LastMovesOutput) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

type LastMovesOutputs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lastmovesoutput []*LastMovesOutput `protobuf:"bytes,1,rep,name=lastmovesoutput,proto3" json:"lastmovesoutput,omitempty"`
}

func (x *LastMovesOutputs) Reset() {
	*x = LastMovesOutputs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LastMovesOutputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LastMovesOutputs) ProtoMessage() {}

func (x *LastMovesOutputs) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LastMovesOutputs.ProtoReflect.Descriptor instead.
func (*LastMovesOutputs) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{10}
}

func (x *LastMovesOutputs) GetLastmovesoutput() []*LastMovesOutput {
	if x != nil {
		return x.Lastmovesoutput
	}
	return nil
}

type GetMapsInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gameid uint32 `protobuf:"varint,1,opt,name=gameid,proto3" json:"gameid,omitempty"`
}

func (x *GetMapsInput) Reset() {
	*x = GetMapsInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMapsInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMapsInput) ProtoMessage() {}

func (x *GetMapsInput) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMapsInput.ProtoReflect.Descriptor instead.
func (*GetMapsInput) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{11}
}

func (x *GetMapsInput) GetGameid() uint32 {
	if x != nil {
		return x.Gameid
	}
	return 0
}

type GetMapsOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Terrainmap  string `protobuf:"bytes,1,opt,name=terrainmap,proto3" json:"terrainmap,omitempty"`
	Featuredmap string `protobuf:"bytes,2,opt,name=featuredmap,proto3" json:"featuredmap,omitempty"`
}

func (x *GetMapsOutput) Reset() {
	*x = GetMapsOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMapsOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMapsOutput) ProtoMessage() {}

func (x *GetMapsOutput) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMapsOutput.ProtoReflect.Descriptor instead.
func (*GetMapsOutput) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{12}
}

func (x *GetMapsOutput) GetTerrainmap() string {
	if x != nil {
		return x.Terrainmap
	}
	return ""
}

func (x *GetMapsOutput) GetFeaturedmap() string {
	if x != nil {
		return x.Featuredmap
	}
	return ""
}

var File_api_proto protoreflect.FileDescriptor

var file_api_proto_rawDesc = []byte{
	0x0a, 0x09, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69,
	0x22, 0x2a, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x22, 0x4d, 0x0a, 0x11,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x73, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x66, 0x65, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x64, 0x6d, 0x61, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x64, 0x6d, 0x61, 0x70, 0x22, 0x40, 0x0a, 0x0e, 0x4a,
	0x6f, 0x69, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x67, 0x61, 0x6d, 0x65, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x67,
	0x61, 0x6d, 0x65, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x22, 0x57, 0x0a,
	0x0f, 0x4a, 0x6f, 0x69, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73,
	0x12, 0x22, 0x0a, 0x0c, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x75, 0x73, 0x65, 0x72, 0x73, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x75, 0x73, 0x65,
	0x72, 0x73, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x64,
	0x6d, 0x61, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x66, 0x65, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x64, 0x6d, 0x61, 0x70, 0x22, 0x40, 0x0a, 0x04, 0x4d, 0x6f, 0x76, 0x65, 0x12, 0x0c,
	0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x64,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x42, 0x0a, 0x09, 0x4d, 0x6f, 0x76, 0x65,
	0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x77, 0x6e, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x70, 0x61, 0x77, 0x6e, 0x69, 0x64, 0x12, 0x1d, 0x0a,
	0x04, 0x6d, 0x6f, 0x76, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x04, 0x6d, 0x6f, 0x76, 0x65, 0x22, 0x6a, 0x0a, 0x0a,
	0x4d, 0x6f, 0x76, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x69, 0x64, 0x12, 0x2c, 0x0a, 0x09, 0x6d, 0x6f,
	0x76, 0x65, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x09, 0x6d,
	0x6f, 0x76, 0x65, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x22, 0x1d, 0x0a, 0x0b, 0x4d, 0x6f, 0x76, 0x65,
	0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x4f, 0x4b, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x02, 0x4f, 0x4b, 0x22, 0x3f, 0x0a, 0x0f, 0x4c, 0x61, 0x73, 0x74, 0x4d,
	0x6f, 0x76, 0x65, 0x73, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x61,
	0x6d, 0x65, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65,
	0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x22, 0xa9, 0x01, 0x0a, 0x0f, 0x4c, 0x61, 0x73,
	0x74, 0x4d, 0x6f, 0x76, 0x65, 0x73, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x70, 0x61, 0x77, 0x6e, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x70, 0x61,
	0x77, 0x6e, 0x69, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x79,
	0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14,
	0x0a, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x72,
	0x6f, 0x75, 0x6e, 0x64, 0x22, 0x52, 0x0a, 0x10, 0x4c, 0x61, 0x73, 0x74, 0x4d, 0x6f, 0x76, 0x65,
	0x73, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x12, 0x3e, 0x0a, 0x0f, 0x6c, 0x61, 0x73, 0x74,
	0x6d, 0x6f, 0x76, 0x65, 0x73, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x61, 0x73, 0x74, 0x4d, 0x6f, 0x76, 0x65,
	0x73, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x52, 0x0f, 0x6c, 0x61, 0x73, 0x74, 0x6d, 0x6f, 0x76,
	0x65, 0x73, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x26, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x4d,
	0x61, 0x70, 0x73, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x61, 0x6d, 0x65,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x69, 0x64,
	0x22, 0x51, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x70, 0x73, 0x4f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x65, 0x72, 0x72, 0x61, 0x69, 0x6e, 0x6d, 0x61, 0x70, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x65, 0x72, 0x72, 0x61, 0x69, 0x6e, 0x6d, 0x61,
	0x70, 0x12, 0x20, 0x0a, 0x0b, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x64, 0x6d, 0x61, 0x70,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x64,
	0x6d, 0x61, 0x70, 0x32, 0xaa, 0x02, 0x0a, 0x0c, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79,
	0x47, 0x61, 0x6d, 0x65, 0x12, 0x3d, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x61,
	0x6d, 0x65, 0x12, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47,
	0x61, 0x6d, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x73, 0x1a, 0x16, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x73, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x08, 0x4a, 0x6f, 0x69, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x12,
	0x13, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x73, 0x1a, 0x14, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x47,
	0x61, 0x6d, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x22, 0x00, 0x12, 0x2f, 0x0a, 0x08,
	0x4d, 0x61, 0x6b, 0x65, 0x4d, 0x6f, 0x76, 0x65, 0x12, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d,
	0x6f, 0x76, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x73, 0x1a, 0x10, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x4d, 0x6f, 0x76, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x22, 0x00, 0x12, 0x3d, 0x0a,
	0x0c, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x73, 0x74, 0x4d, 0x6f, 0x76, 0x65, 0x73, 0x12, 0x14, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x4c, 0x61, 0x73, 0x74, 0x4d, 0x6f, 0x76, 0x65, 0x73, 0x49, 0x6e, 0x70,
	0x75, 0x74, 0x73, 0x1a, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x61, 0x73, 0x74, 0x4d, 0x6f,
	0x76, 0x65, 0x73, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x07,
	0x47, 0x65, 0x74, 0x4d, 0x61, 0x70, 0x73, 0x12, 0x11, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65,
	0x74, 0x4d, 0x61, 0x70, 0x73, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x12, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x70, 0x73, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x00,
	0x42, 0x0c, 0x5a, 0x0a, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData = file_api_proto_rawDesc
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_rawDescData)
	})
	return file_api_proto_rawDescData
}

var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_proto_goTypes = []interface{}{
	(*CreateGameInputs)(nil),  // 0: api.CreateGameInputs
	(*CreateGameOutputs)(nil), // 1: api.CreateGameOutputs
	(*JoinGameInputs)(nil),    // 2: api.JoinGameInputs
	(*JoinGameOutputs)(nil),   // 3: api.JoinGameOutputs
	(*Move)(nil),              // 4: api.Move
	(*MoveInput)(nil),         // 5: api.MoveInput
	(*MoveInputs)(nil),        // 6: api.MoveInputs
	(*MoveOutputs)(nil),       // 7: api.MoveOutputs
	(*LastMovesInputs)(nil),   // 8: api.LastMovesInputs
	(*LastMovesOutput)(nil),   // 9: api.LastMovesOutput
	(*LastMovesOutputs)(nil),  // 10: api.LastMovesOutputs
	(*GetMapsInput)(nil),      // 11: api.GetMapsInput
	(*GetMapsOutput)(nil),     // 12: api.GetMapsOutput
}
var file_api_proto_depIdxs = []int32{
	4,  // 0: api.MoveInput.move:type_name -> api.Move
	5,  // 1: api.MoveInputs.moveinput:type_name -> api.MoveInput
	9,  // 2: api.LastMovesOutputs.lastmovesoutput:type_name -> api.LastMovesOutput
	0,  // 3: api.StrategyGame.CreateGame:input_type -> api.CreateGameInputs
	2,  // 4: api.StrategyGame.JoinGame:input_type -> api.JoinGameInputs
	6,  // 5: api.StrategyGame.MakeMove:input_type -> api.MoveInputs
	8,  // 6: api.StrategyGame.GetLastMoves:input_type -> api.LastMovesInputs
	11, // 7: api.StrategyGame.GetMaps:input_type -> api.GetMapsInput
	1,  // 8: api.StrategyGame.CreateGame:output_type -> api.CreateGameOutputs
	3,  // 9: api.StrategyGame.JoinGame:output_type -> api.JoinGameOutputs
	7,  // 10: api.StrategyGame.MakeMove:output_type -> api.MoveOutputs
	10, // 11: api.StrategyGame.GetLastMoves:output_type -> api.LastMovesOutputs
	12, // 12: api.StrategyGame.GetMaps:output_type -> api.GetMapsOutput
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGameInputs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGameOutputs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinGameInputs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinGameOutputs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Move); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveInputs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveOutputs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LastMovesInputs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LastMovesOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LastMovesOutputs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMapsInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMapsOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_rawDesc = nil
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
